controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_wheel_controller:
      type: effort_controllers/JointEffortController
      joint: left_wheel_joint
    right_wheel_controller:
      type: effort_controllers/JointEffortController
      joint: right_wheel_joint