controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    left_wheel_controller:
      type: effort_controllers/JointCommandController
      joints: [left_wheel_joint]  # Use list syntax
      command_interfaces: [effort]
      state_interfaces: [position, velocity]  # Add state interfaces
    right_wheel_controller:
      type: effort_controllers/JointCommandController
      joints: [right_wheel_joint]
      command_interfaces: [effort]
      state_interfaces: [position, velocity]