<?xml version="1.0"?>
<robot name="balance_bot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Parameters -->
  <xacro:property name="wheel_radius" value="0.05"/>
  <xacro:property name="wheel_width" value="0.02"/>
  <xacro:property name="chassis_height" value="0.2"/>
  <xacro:property name="chassis_width" value="0.1"/>
  <xacro:property name="chassis_depth" value="0.05"/>

  <!-- Chassis -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${chassis_width} ${chassis_depth} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
      <material name="gray">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${chassis_width} ${chassis_depth} ${chassis_height}"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
      <origin xyz="0 0 ${chassis_height/2}" rpy="0 0 0"/>
    </inertial>
  </link>

  <!-- Left wheel -->
  <link name="left_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 ${chassis_width/2 + wheel_width/2} 0" rpy="0 1.5708 0"/>
      <material name="black">
        <color rgba="0 0 0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 ${chassis_width/2 + wheel_width/2} 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <!-- Right wheel -->
  <link name="right_wheel">
    <visual>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 -${chassis_width/2 + wheel_width/2} 0" rpy="0 1.5708 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <origin xyz="0 -${chassis_width/2 + wheel_width/2} 0" rpy="0 1.5708 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.001" ixy="0.0" ixz="0.0"
               iyy="0.001" iyz="0.0"
               izz="0.001"/>
    </inertial>
  </link>

  <!-- Wheel joints -->
  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel"/>
    <origin xyz="0 ${chassis_width/2 + wheel_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel"/>
    <origin xyz="0 -${chassis_width/2 + wheel_width/2} 0" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <!-- IMU -->
  <link name="imu_link">
    <visual>
      <geometry>
        <box size="0.02 0.02 0.02"/>
      </geometry>
      <origin xyz="0 0 ${chassis_height}" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0 0 1.0 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="imu_joint" type="fixed">
    <parent link="base_link"/>
    <child link="imu_link"/>
    <origin xyz="0 0 ${chassis_height}" rpy="0 0 0"/>
  </joint>

  <!-- Encoders on motors (fixed joints) -->
  <link name="left_encoder"/>
  <joint name="left_encoder_joint" type="fixed">
    <parent link="left_wheel"/>
    <child link="left_encoder"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="right_encoder"/>
  <joint name="right_encoder_joint" type="fixed">
    <parent link="right_wheel"/>
    <child link="right_encoder"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

</robot>
